title: Hezbollah
description: "حزب الله | Party of GodAllah™ - Progressive Wing"
url: hezbollah.ml
theme_color: white
markdown: kramdown
plugins:
  - jekyll-seo-tag
social:
  description: "حزب الله | Party of GodAllah™ - Progressive Wing"
  og_description: "حزب الله | Party of GodAllah™ - Progressive Wing"
  og_image: /assets/og-image.png
  og_title: Hezbollah
  og_type: website
