title: Hezbollah
description: حزب الله | Party of God<sup>Allah™</sup> - Progressive Wing
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hezbollah.ml" # the base hostname & protocol for your site, e.g. http://example.com

theme_color: white

markdown: kramdown
